# Generated by Django 4.0.4 on 2022-05-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('head1', models.CharField(default='', max_length=20)),
                ('body1', models.CharField(default='', max_length=500)),
                ('head2', models.CharField(default='', max_length=20)),
                ('body2', models.CharField(default='', max_length=500)),
                ('head3', models.CharField(default='', max_length=20)),
                ('body3', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
