# Generated by Django 4.0.4 on 2022-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontent',
            name='head1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='head2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='head3',
            field=models.CharField(default='', max_length=100),
        ),
    ]
