# Generated by Django 4.0.4 on 2022-05-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcontent_head1_alter_blogcontent_head2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
