# Generated by Django 4.0.4 on 2022-05-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('desc', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=40)),
                ('phoneno', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='shopping/images'),
        ),
    ]
