# Generated by Django 4.0.4 on 2022-05-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_contact_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('items_json', models.CharField(max_length=5000)),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=40)),
                ('phoneno', models.CharField(default='', max_length=40)),
                ('zip_code', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
