# Generated by Django 4.0.4 on 2022-05-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_orders_alter_contact_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
